tenant_name: tenant1
variables:
  - "defaults.yml"
  - "{environment}.yml"
environments:
  - dev.yml
  - prod.yml
repositories:
  test_repo1:
    type: local
    url: local_path
configs:
  - template_file: template1.tpl
    variables:
      - tenant_variable: aaa
        tpl_variable: template_var1
      - tenant_variable: bbb
        tpl_variable: template_var2
      - tenant_variable: ccc
        tpl_variable: template_var3
      - tenant_variable: ddd
        tpl_variable: template_var4
    destination_repo: gitops-configserver-tests
    destination_filename: tenant1/config1-{{matrix.os}}-{{matrix.version}}-{{matrix.python_version}}-{{environment}}.yml
    environment: prod
    matrix:
      os: [ubuntu-22.04, ubuntu-20.04]
      version: [10, 12, 14]
      python_version: "{{ python_version }}"
    matrix_include:
      - os: 'ubuntu-22.04'
        version: '10'
        python_version: 'python3.7'
  - template_file: template1.tpl
    variables:
      - tenant_variable: aaa
        tpl_variable: template_var1
      - tenant_variable: bbb
        tpl_variable: template_var2
      - tenant_variable: ccc
        tpl_variable: template_var3
      - tenant_variable: ddd
        tpl_variable: template_var4
    destination_repo: gitops-configserver-tests
    destination_filename: config1-{{environment}}.yml
    environment: prod
