tenant_name: tenant1
hierarchy:
  - nodes/{nodes}.yaml
  - environments/{environment}.yaml
  - defaults.yaml
repositories:
  test_repo1:
    type: local
    url: local_path
configs:
  - template_file: template1.tpl
    variables:
      - tenant_variable: aaa
        tpl_variable: aaa
      - tenant_variable: bbb
        tpl_variable: bbb
      - tenant_variable: ccc
        tpl_variable: ccc
      - tenant_variable: ddd
        tpl_variable: ddd
    destination_repo: gitops-configserver-tests
    destination_filename: tenant1/config1-{{matrix.os}}-{{matrix.version}}-{{matrix.python_version}}-{{environment}}.yaml
    environment: prod
    matrix:
      os: [ubuntu-22.04, ubuntu-20.04]
      version: [10, 12, 14]
      python_version: "{{ python_version }}"
    matrix_include:
      - os: 'ubuntu-22.04'
        version: '10'
        python_version: 'python3.7'
  - template_file: template1.tpl
    variables:
      - tenant_variable: aaa
        tpl_variable: aaa
      - tenant_variable: bbb
        tpl_variable: bbb
      - tenant_variable: ccc
        tpl_variable: ccc
      - tenant_variable: ddd
        tpl_variable: ddd
    destination_repo: gitops-configserver-tests
    destination_filename: config1-{{environment}}.yaml
    environment: prod
