tenant_name: tenant1
variables:
  - "defaults.yml"
  - "{environment}.yml"
environments:
  - dev.yml
  - prod.yml
repositories:
  - repo_name: test_repo1
url: ../test_repo1
configs:
  - template_file: template1.tpl
    variables:
      - tenant_variable: aaa
        tpl_variable: template_var1
      - tenant_variable: bbb
        tpl_variable: template_var2
      - tenant_variable: ccc
        tpl_variable: template_var3
      - tenant_variable: ddd
        tpl_variable: template_var4
    repo_name: test_repo1
    destination_filename: config1.yml
    environment: prod

