tenants:
- tenant1
repositories:
  test_repo1:
    type: local
    url: local_path
  gitops-configserver-tests:
    type: github
    url: github.com/pprzetacznik/gitops-configserver-tests.git
  gitops-configserver-tests-git:
    type: git
    url: git@github.com:pprzetacznik/gitops-configserver-tests.git
hierarchy:
- nodes/{node}.yml
- environments/{environment}.yml
- defaults.yml
