name: gitops-configserver Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Documentation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_API_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Deploy package
      run: |
        pip install twine wheel
        pip install build setuptools
        python -m build --sdist --wheel
        twine upload dist/* --skip-existing
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        tag_name: ${{ github.ref }}
        release_name: gitops-configserver ${{ github.ref }}
        body: |
          Changes in this release:
          - ${{ github.event.head_commit.message }}
        draft: true
        prerelease: false
