name: gitops-configserver

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  build:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python packages
      run: |
        pip install pip --upgrade
        pip install -r requirements.txt
    - name: Run mypy
      run: |
        pip install -r requirements-mypy.txt
        mypy
    - name: Run tests
      run: |
        ./run_tests.sh
    - name: Run config
      run: |
        ./run.sh
    - name: Generate documentation
      run: |
        sphinx-build -M html docs docs_build
